# This file was generated by tools/update/update.py

require tacd-webinterface.inc

# Commit 71aae7abee147883b9c6e19b7119800c1b395b90 created 2025-08-29 13:22:33 +0200
SRCBRANCH = "main"
SRCREV = "71aae7abee147883b9c6e19b7119800c1b395b90"
