# This file was generated by tools/update/update.py

require gitlab-runner.inc

# Git tag v18.3.1 pointing at a commit from 2025-09-04 15:24:16 +0000
SRCBRANCH = "18-3-stable"
SRCREV = "40e11dbd8f6c491ad64533c5a43630378e305577"
