# This file was generated by tools/update/update.py

require gitlab-runner.inc

# Git tag v18.8.0 pointing at a commit from 2026-01-15 15:55:25 +0000
SRCBRANCH = "18-8-stable"
SRCREV = "9ffb4aa066204dc1b5f80b3043c30936002434fb"
