# This file was generated by tools/update/update.py

require gitlab-runner.inc

# Git tag v18.6.3 pointing at a commit from 2025-11-28 21:25:01 +0000
SRCBRANCH = "18-6-stable"
SRCREV = "dbac4904553947d823cf632ac928023ec2c9a987"
