# This file was generated by tools/update/update.py

require gitlab-runner.inc

# Git tag v18.7.0 pointing at a commit from 2025-12-18 17:19:24 +0000
SRCBRANCH = "18-7-stable"
SRCREV = "901991dd22896ca37d58f46f8107bafc30fe2384"
