# This file was generated by tools/update/update.py

require gitlab-runner.inc

# Git tag v18.4.0 pointing at a commit from 2025-09-12 20:51:41 +0000
SRCBRANCH = "18-4-stable"
SRCREV = "139a0ac033907890894642625cdfabf215c614fd"
