# This file was generated by tools/update/update.py

require gitlab-runner.inc

# Git tag v18.6.5 pointing at a commit from 2025-12-05 21:20:48 +0000
SRCBRANCH = "18-6-stable"
SRCREV = "5908bc192c2cf236e6696403e852c518a6fd4f2f"
