# This file was generated by tools/update/update.py

require gitlab-runner.inc

# Git tag v18.3.1 pointing at a commit from 2025-09-04 15:24:16 +0000
SRCBRANCH = "18-3-stable"
SRCREV = "5a021a1c14edadc683ee4b1f0a00182ec3ee636a"
