# This file was generated by tools/update/update.py

require gitlab-runner.inc

# Git tag v18.6.6 pointing at a commit from 2025-12-09 21:36:46 +0000
SRCBRANCH = "18-6-stable"
SRCREV = "df85dadfe31bd09f5029e343b00b8656a6255319"
