# This file was generated by tools/update/update.py

# Git tag bcu_1.1.125 pointing at a commit from 2025-11-26 18:56:57 +0800
SRCBRANCH = "master"
SRCREV = "9a06836d6d6dfb61e4951d69c92b5a2085d28721"
PV = "1.1.125"

SRC_URI:remove = "file://0001-CMakeLists-do-not-use-vendored-libcurl.patch"
