# This file was generated by tools/update/update.py

# Git tag bcu_1.1.120 pointing at a commit from 2025-07-29 17:33:42 +0800
SRCBRANCH = "master"
SRCREV = "394a01f742e640c3aff0e87d4e0529e57d977ec5"
PV = "1.1.120"

SRC_URI:remove = "file://0001-CMakeLists-do-not-use-vendored-libcurl.patch"
