# This file was generated by tools/update/update.py

# Git tag bcu_1.1.121 pointing at a commit from 2025-10-20 11:04:24 +0800
SRCBRANCH = "master"
SRCREV = "523d6fd8c75e8c82a987ec23c7674ec12990762a"
PV = "1.1.121"

SRC_URI:remove = "file://0001-CMakeLists-do-not-use-vendored-libcurl.patch"
