# This file was generated by tools/update/update.py

require ripgrep.inc

# Git tag 15.0.0 pointing at a commit from 2025-10-15 23:07:50 -0400
SRCBRANCH = "master"
SRCREV = "3a612f88b805e14aef45bfa43e25a54abc6297fc"
