# This file was generated by tools/update/update.py

require github-act-runner.inc

# Git tag v0.13.0 pointing at a commit from 2026-01-23 14:54:24 +0100
SRCBRANCH = "main"
SRCREV = "c934667526f602e5732e7072fcd53b36cf044e37"
