# This file was generated by tools/update/update.py

require github-act-runner.inc

# Git tag v0.11.0 pointing at a commit from 2025-09-05 17:51:03 +0200
SRCBRANCH = "main"
SRCREV = "80ff95f2271bd9d444ac8b09057250941344010b"
