name: shellcheck

on:
  pull_request:
    paths:
      - '.github/workflows/shellcheck.yml'
      - '**.sh'

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt update
      - run: sudo apt install shellcheck
      - run: shellcheck --exclude=SC1091 --color=always --enable=all $(find meta-lxatac-bsp meta-lxatac-software -name "*.sh")
