name: update

on:
  schedule:
    - cron: '10 21 * * 2'
  workflow_dispatch:

jobs:
  update:
    name: update recipes
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Create a new branch
        run: git checkout -b "update/recipes-$(date +%Y%m%d)"

      - name: Run update script
        run: python3 -u tools/update/update.py tools/update/recipes.yaml

      - name: Check for changes
        run: |
          if git diff --name-only --exit-code; then
            HAVE_CHANGES="false"
          else
            HAVE_CHANGES="true"
          fi

      - name: Update rust dependencies
        if: ${{ env.HAVE_CHANGES == 'true' }}
        run: |
          sudo apt instal chrpath diffstat
          source oe-init-build-env
          bitbake -c update_crates bottom tacd ripgrep

      - name: Create and push commit
        if: ${{ env.HAVE_CHANGES == 'true' }}
        run: |
          git add .
          git commit -m "Recipe update for $(date +%Y-%m-%d)"
          git push -u origin

      - name: Create pull request
        if: ${{ env.HAVE_CHANGES == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr --base "${{ github.ref_name }}" --fill
