# This file was generated by tools/update/update.py

require bottom.inc

# Git tag 0.11.1 pointing at a commit from 2025-08-14 23:56:41 -0400
SRCBRANCH = "main"
SRCREV = "2578f20ce542047e3906ef87334ce15fbb53c15a"
